### ISSUE TITLE
Mac issues

### ISSUE THREAD

**Issue by oleghind** [ivanakimov/hashids.php#61] opened 2016-02-25 15:54 UTC
Having this issue on 4 macs, but not on Ubuntu 14.04:

All math libs are on, but when trying to use a number that has more than 10 digits I get a blank screen in the browser, without any errors (php error reporting is on, error logs remain empty).

To fix it I have to make this change manually:
`private $_max_int_value = PHP_INT_MAX;`

or

`$this->_lower_max_int_value = PHP_INT_MAX;`

probably this variable 
`$this->_lower_max_int_value`
must go after this block:
`       
 if ($this->_math_functions) {
  $this->_max_int_value = PHP_INT_MAX;
}
` 

and not before

**Comment by wjgilmore** [comment] 2016-04-13 15:28
I'd just like to chime in as I'm experiencing the same issue running 1.0.6 on a Homestead VM. Numbers more than 10 digits result in `Hashids::encode()` returning an empty string, whereas numbers less than 10 digits produce expected encoding results.

Per the OP's mention of Macs though, what's really strange is the problem only arises when running `Hashids::encode()` on an app hosted on Homestead; if I use my local OS X-hosted Psy shell PHP interactive environment to run the same Hashids::encode() command with a 10+ digit number, it produces the expected result.

**Comment by wjgilmore** [comment] 2016-04-13 16:01
Duh maybe if I'd read the README the issue would be obvious. If anybody else is having this issue read the README section "Big Numbers".

**Comment by ChristianVermeulen** [comment] 2016-05-03 11:14
So, i checked the big number section... I have Bcmath installed and verified the upper limit is increased with `$hashids->get_max_int_value()` which returns `9223372036854775807`.

I'm using a timestamp as int to generate the hash (no need for decoding, I just need a userfriendly unique string for copying over by hand). The timestamp has 10 digits. When I use anything below 10 digits it works fine, but as soon as I hit 10 or more it crashes and I get the blank screen as well.

- OSX El Capitan
- PHP 7.0.4 (phposx-liip)
- Apache 2.4.18
- Symfony 3

![screenshot 2016-05-03 13 13 47](https://cloud.githubusercontent.com/assets/1062751/14981644/ebad2cca-1130-11e6-8664-bac807acac31.png)

**Comment by ivanakimov** [comment] 2016-05-03 17:17
So, if you're having issues with big numbers, please check your setup. Also, from `README`:

> It will then use regular arithmetic on numbers less than 1 billion (because it's faster), and one of these libraries if greater than. GMP takes precedence over BCMath.

10 digits and up: the library is using either GMP or BCMath. Those functions are `gmp_add`, `gmp_div`, `gmp_strval` and `bcadd`, `bcdiv`, `strval`. Try simple arithmetic with those functions manually to verify they're working for you.

This PHP library has been tested with big numbers, and they worked as expected before; so unless something changed in PHP or those libraries, the issue is probably in your setup.

Closing for now, please re-open if you find something in code.

**Comment by ChristianVermeulen** [comment] 2016-05-09 11:11
I just checked if those functions are available and seem to be:

```
echo function_exists ( 'gmp_add' );
echo '<br/>';
echo function_exists ( 'gmp_div' );
echo '<br/>';
echo function_exists ( 'gmp_strval' );
echo '<br/>';
echo function_exists ( 'bcadd' );
echo '<br/>';
echo function_exists ( 'bcdiv' );
echo '<br/>';
echo function_exists ( 'strval' );
```

outputs:
```
1
1
1
1
1
1
```

If you have any others tests you would like me to run, let me know.
But for now it seems the issue is definitely not resolved :(

**Comment by ivanakimov** [comment] 2016-05-09 17:14
> but as soon as I hit 10 or more it crashes and I get the blank screen as well

What's the error you're getting in the error log?

**Comment by oleghind** [comment] 2016-05-09 17:48
There is nothing interesting in logs:

> AH00052: child pid 49418 exit signal Segmentation fault (11)

No matter which OS version, PHP version or apache version. Maybe a bug in mathlibs.

To anyone who wants to use this library on Mac use the fix from the first message.

**Comment by ivanakimov** [comment] 2016-05-09 18:28
Okay, so far I'm unable to reproduce, but will have to investigate.

**Comment by vinkla** [comment] 2016-10-11 08:43
@oleghind are you still having issues with this?

**Comment by vinkla** [comment] 2016-10-14 07:56
Closing this since we can't reproduce it. If anyone are still having issues with this please open a new issue and we'll take a look at it!

**Closed by vinkla** 2016-10-14 07:56 UTC

**Comment by darraghenright** [comment] 2016-12-24 10:51
Hi guys.

Firstly, I'd like to apologise for commenting on a closed issue.

I encountered the same problem reported by @ChristianVermeulen et al.

I'm running [LIIP OSX](https://php-osx.liip.ch) packages  7.0.8 and 7.1.0 on OSX El Capitan. These packages include both GMP and BCMath.

The number I tried to encode was very large - over 1 billion - but still much lower than `PHP_INT_MAX` as displayed on my system.

I dug into it a little and found that `gmp_div` is the culprit. It immediately segfaults, irrespective of the size of the values passed into it. The other `gmp` functions operate without error.

I adjusted the source of `\Hashids\Hashids::__construct()` to prefer the BCMath functions instead and found that they work fine.

Same goes for the stock El Capitan PHP 5.5, which only has BCMath installed.

This is clearly environmental and is nothing to do with the Hashids codebase itself, but I thought I'd report on the above findings in case it's useful to anyone else googling this issue in future.

**Comment by ivanakimov** [comment] 2016-12-24 18:14
@darraghenright thanks for the info, useful 👍

**Comment by moopa** [comment] 2017-09-07 15:09
Apologies for responding to a closed issue, but for anyone else running El-Capitan / OSX with liip PHP, I can confirm that the problem is with gmp_div_q which seg faults and this is why encode() fails for this package. As work around, adjust the divide function in src/Math.php and remove the call to gmp_div_q

`public static function divide($a, $b)
{
    /*
    if (function_exists('gmp_div_q')) {
        return gmp_div_q($a, $b);
    }*/

    return bcdiv($a, $b, 0);
}`

**Comment by deanc** [comment] 2017-10-12 07:56
I can confirm I'm also having this issue on mac. Would it be possible to get a fix integrated?

**Comment by guilleferrer** [comment] 2017-10-13 10:32
I can also confirm having this issue on mac. Thank god @moopa responded to a closed issue!! 
In my case there was a segmentation fall when invoking:

````
gmp_div_q(3, 44);
```

Clearly an environment problem using ```gmp.php``` in Mac but still don't know how to fix it.
